- name: Docker is present
  yum:
    name: http://yum.dockerproject.org/repo/main/centos/7/Packages/docker-engine-1.8.2-1.el7.centos.x86_64.rpm
    state: present
  tags: [docker]

- name: Python-pip is present
  yum:
    name: python-pip
    state: present
  tags: [docker]

- name: Docker-py is present
  pip:
    name: docker-py
    version: 0.4.0
    state: present
  tags: [docker]
